# .streamlit/secrets.toml
groq_api_key = "GROQ_NATURETRACE"
hf_token = "HF_TOKEN"
snowflake_account = "ELVORXO-FX00525"
snowflake_user = "nailasadia"
snowflake_password = "N@il@1234567890"
snowflake_warehouse = "your_warehouse"
snowflake_database = "your_database"
snowflake_schema = "your_schema"
google_maps_key = "your_google_maps_api_key"