# .streamlit/secrets.toml
groq_api_key = "GROQ_NATURETRACE"
hf_token = "HF_TOKEN"
snowflake_account = "ELVORXO-FX00525"
snowflake_user = "nailasadia"
snowflake_password = "N@il@1234567890"
snowflake_warehouse = "naturetrace_wh"
snowflake_database = "naturetrace_db"
snowflake_schema = "naturetrace_s"
google_maps_key = "GOO_TOKEN"