# .streamlit/secrets.toml
groq_api_key = "your_groq_api_key"
hf_token = "your_huggingface_token"
snowflake_account = "your_snowflake_account"
snowflake_user = "your_username"
snowflake_password = "your_password"
snowflake_warehouse = "your_warehouse"
snowflake_database = "your_database"
snowflake_schema = "your_schema"
google_maps_key = "your_google_maps_api_key"